[package]
name = "rustc-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
bridge-ir = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
